# Generated by Django 3.2.6 on 2021-08-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_snippet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='original_snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='snippets.snippet'),
        ),
    ]
