# Generated by Django 3.2.6 on 2021-08-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_snippet_original_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='copy_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
