# Generated by Django 3.2.6 on 2021-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_snippet_original_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(blank=True, choices=[('markup', 'MARKUP'), ('css', 'CSS'), ('clike', 'C+'), ('javascript', 'JAVASCRIPT'), ('csharp', 'C#'), ('csv', 'CSV'), ('git', 'GIT'), ('http', 'HTTP'), ('java', 'JAVA'), ('python', 'PYTHON'), ('sql', 'SQL')], default=None, max_length=11, null=True),
        ),
    ]
