# Generated by Django 3.2.6 on 2021-08-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_snippet_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(blank=True, choices=[('markup', 'MARKUP'), ('css', 'CSS'), ('clike', 'C++'), ('javascript', 'JAVASCRIPT'), ('csharp', 'C#'), ('csv', 'CSV'), ('git', 'GIT'), ('http', 'HTTP'), ('java', 'JAVA'), ('python', 'PYTHON'), ('sql', 'SQL')], default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='original_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_copies', to='snippets.snippet'),
        ),
    ]
