# Generated by Django 3.2.6 on 2021-08-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_snippet_copy_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='copy_count',
            field=models.IntegerField(null=True),
        ),
    ]
