# Generated by Django 3.2.6 on 2021-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20210826_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='copy_count',
            field=models.IntegerField(default=0),
        ),
    ]
